modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "numismaticscalculator"
version = "${version}"
displayName = "NumismaticsCalculator"
authors = ""
description = '''

'''
logoFile = "assets/numismaticscalculator/icon.png"

[[dependencies.numismaticscalculator]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.numismaticscalculator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

