modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "numismaticscalculator"
version = "${version}"
displayName = "Numismatics Calculator"
authors = "Daylight"
description = '''
A client-side utility mod that adds a calculation menu for coin items from the mod "Create: Numismatics".
'''
logoFile = "assets/numismaticscalculator/icon.png"

[[dependencies.numismaticscalculator]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.numismaticscalculator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.numismaticscalculator]]
modId="numismatics"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"
